# Terrain
minecraft:stone: 1
minecraft:deepslate: 2
minecraft:cobbled_deepslate: 2
minecraft:calcite: 5
minecraft:tuff: 2
minecraft:grass_block: 1
minecraft:dirt: 1
minecraft:podzol: 1
minecraft:rooted_dirt: 1
minecraft:cobblestone: 1
minecraft:bedrock: -1
minecraft:sand: 5
minecraft:red_sand: 5
minecraft:gravel: 5
minecraft:coal_ore: 25
minecraft:deepslate_coal_ore: 25
minecraft:iron_ore: 50
minecraft:deepslate_iron_ore: 50
minecraft:copper_ore: 20
minecraft:deepslate_copper_ore: 20
minecraft:gold_ore: 100
minecraft:deepslate_gold_ore: 100
minecraft:redstone_ore: 50
minecraft:deepslate_redstone_ore: 50
minecraft:emerald_ore: 1000
minecraft:deepslate_emerald_ore: 1000
minecraft:lapis_ore: 50
minecraft:deepslate_lapis_ore: 50
minecraft:diamond_ore: -1
minecraft:deepslate_diamond_ore: -1
minecraft:pointed_dripstone: 1

# Saplings
minecraft:oak_sapling: 20
minecraft:spruce_sapling: 20
minecraft:birch_sapling: 20
minecraft:jungle_sapling: 20
minecraft:acacia_sapling: 20
minecraft:dark_oak_sapling: 20

# Nether
minecraft:crimson_nylium: 1
minecraft:warped_nylium: 1
minecraft:nether_gold_ore: 100
minecraft:nether_quartz_ore: 75
minecraft:ancient_debris: 2000
minecraft:budding_amethyst: -1
minecraft:exposed_copper: 175
minecraft:weathered_copper: 115
minecraft:oxidized_copper: 100
minecraft:netherrack: 1
minecraft:soul_sand: 1
minecraft:soul_soil: 1
minecraft:basalt: 1
minecraft:smooth_basalt: 1
minecraft:blackstone: 1
minecraft:crying_obsidian: 200
minecraft:gilded_blackstone: 1
minecraft:cracked_polished_blackstone_bricks: 1

# Wood
minecraft:oak_log: 20
minecraft:spruce_log: 20
minecraft:birch_log: 20
minecraft:jungle_log: 20
minecraft:acacia_log: 20
minecraft:dark_oak_log: 20
minecraft:crimson_stem: 20
minecraft:warped_stem: 20
minecraft:stripped_oak_log: 20
minecraft:stripped_spruce_log: 20
minecraft:stripped_birch_log: 20
minecraft:stripped_jungle_log: 20
minecraft:stripped_acacia_log: 20
minecraft:stripped_dark_oak_log: 20
minecraft:stripped_crimson_stem: 20
minecraft:stripped_warped_stem: 20
minecraft:oak_leaves: 1
minecraft:spruce_leaves: 1
minecraft:birch_leaves: 1
minecraft:jungle_leaves: 1
minecraft:acacia_leaves: 1
minecraft:dark_oak_leaves: 1
minecraft:azalea_leaves: 1
minecraft:flowering_azalea_leaves: 1
minecraft:shroomlight: 20
minecraft:honeycomb: 20

# Plants
minecraft:glass: 10
minecraft:cobweb: 10
minecraft:grass: 1
minecraft:fern: 1
minecraft:azalea: 1
minecraft:flowering_azalea: 1
minecraft:dead_bush: 1
minecraft:seagrass: 1
minecraft:sea_pickle: 1
minecraft:dandelion: 1
minecraft:poppy: 1
minecraft:blue_orchid: 1
minecraft:allium: 1
minecraft:azure_bluet: 1
minecraft:red_tulip: 1
minecraft:orange_tulip: 1
minecraft:white_tulip: 1
minecraft:pink_tulip: 1
minecraft:oxeye_daisy: 1
minecraft:cornflower: 1
minecraft:lily_of_the_valley: 1
minecraft:wither_rose: 100
minecraft:spore_blossom: 1
minecraft:brown_mushroom: 1
minecraft:red_mushroom: 1
minecraft:crimson_fungus: 1
minecraft:warped_fungus: 1
minecraft:crimson_roots: 10
minecraft:warped_roots: 10
minecraft:nether_sprouts: 1
minecraft:weeping_vines: 1
minecraft:twisting_vines: 1
minecraft:sugar_cane: 5
minecraft:kelp: 5
minecraft:moss_block: 5
minecraft:hanging_roots: 5
minecraft:big_dripleaf: 1
minecraft:small_dripleaf: 1
minecraft:bamboo: 5
minecraft:cactus: 5
minecraft:pumpkin: 5
minecraft:carved_pumpkin: 5
minecraft:red_mushroom_block: 5
minecraft:mushroom_stem: 5
minecraft:vine: 5
minecraft:glow_lichen: 5
minecraft:mycelium: 1
minecraft:lily_pad: 10
minecraft:sunflower: 1
minecraft:lilac: 1
minecraft:rose_bush: 1
minecraft:peony: 1
minecraft:tall_grass: 1
minecraft:large_fern: 1
minecraft:turtle_egg: 50
minecraft:cocoa_beans: 5
minecraft:nether_wart: 5
minecraft:small_amethyst_bud: 5
minecraft:medium_amethyst_bud: 10
minecraft:large_amethyst_bud: 20
minecraft:amethyst_cluster: 100
minecraft:brown_mushroom_block: 1

# Special building blocks
minecraft:petrified_oak_slab: -1
minecraft:smooth_quartz: 80
minecraft:smooth_red_sandstone: 20
minecraft:smooth_sandstone: 20
minecraft:smooth_stone: 4
minecraft:obsidian: 100
minecraft:spawner: -1
minecraft:farmland: 1
minecraft:ice: 1

# Stone variants
minecraft:infested_stone: 1
minecraft:infested_cobblestone: 1
minecraft:infested_stone_bricks: 1
minecraft:infested_mossy_stone_bricks: 1
minecraft:infested_cracked_stone_bricks: 1
minecraft:infested_chiseled_stone_bricks: 1
minecraft:infested_deepslate: 1
minecraft:cracked_stone_bricks: 1
minecraft:cracked_deepslate_bricks: 1
minecraft:cracked_deepslate_tiles: 1
minecraft:cracked_nether_bricks: 1

# End
minecraft:chorus_plant: 10
minecraft:chorus_flower: 1
minecraft:end_stone: 1
minecraft:dragon_egg: -1

# Interactive blocks
minecraft:chipped_anvil: 800
minecraft:damaged_anvil: 400
minecraft:bell: 200
minecraft:bee_nest: 200

# Terracotta
minecraft:terracotta: -1

# Shulker boxes (disabled for safety)
minecraft:white_shulker_box: -1
minecraft:orange_shulker_box: -1
minecraft:magenta_shulker_box: -1
minecraft:light_blue_shulker_box: -1
minecraft:yellow_shulker_box: -1
minecraft:lime_shulker_box: -1
minecraft:pink_shulker_box: -1
minecraft:gray_shulker_box: -1
minecraft:light_gray_shulker_box: -1
minecraft:cyan_shulker_box: -1
minecraft:purple_shulker_box: -1
minecraft:blue_shulker_box: -1
minecraft:brown_shulker_box: -1
minecraft:green_shulker_box: -1
minecraft:red_shulker_box: -1
minecraft:black_shulker_box: -1

# Terracotta
minecraft:white_glazed_terracotta: 15
minecraft:orange_glazed_terracotta: 15
minecraft:magenta_glazed_terracotta: 15
minecraft:light_blue_glazed_terracotta: 15
minecraft:yellow_glazed_terracotta: 15
minecraft:lime_glazed_terracotta: 15
minecraft:pink_glazed_terracotta: 15
minecraft:gray_glazed_terracotta: 15
minecraft:light_gray_glazed_terracotta: 15
minecraft:cyan_glazed_terracotta: 15
minecraft:purple_glazed_terracotta: 15
minecraft:blue_glazed_terracotta: 15
minecraft:brown_glazed_terracotta: 15
minecraft:green_glazed_terracotta: 15
minecraft:red_glazed_terracotta: 15
minecraft:black_glazed_terracotta: 15

# Concrete
minecraft:white_concrete: 12
minecraft:orange_concrete: 12
minecraft:magenta_concrete: 12
minecraft:light_blue_concrete: 12
minecraft:yellow_concrete: 12
minecraft:lime_concrete: 12
minecraft:pink_concrete: 12
minecraft:gray_concrete: 12
minecraft:light_gray_concrete: 12
minecraft:cyan_concrete: 12
minecraft:purple_concrete: 12
minecraft:blue_concrete: 12
minecraft:brown_concrete: 12
minecraft:green_concrete: 12
minecraft:red_concrete: 12
minecraft:black_concrete: 12

# Coral
minecraft:dead_tube_coral_block: 1
minecraft:dead_brain_coral_block: 1
minecraft:dead_bubble_coral_block: 1
minecraft:dead_fire_coral_block: 1
minecraft:dead_horn_coral_block: 1
minecraft:tube_coral_block: 20
minecraft:brain_coral_block: 20
minecraft:bubble_coral_block: 20
minecraft:fire_coral_block: 20
minecraft:horn_coral_block: 20
minecraft:tube_coral: 20
minecraft:brain_coral: 20
minecraft:bubble_coral: 20
minecraft:fire_coral: 20
minecraft:horn_coral: 20
minecraft:dead_brain_coral: 1
minecraft:dead_bubble_coral: 1
minecraft:dead_fire_coral: 1
minecraft:dead_horn_coral: 1
minecraft:dead_tube_coral: 1
minecraft:tube_coral_fan: 20
minecraft:brain_coral_fan: 20
minecraft:bubble_coral_fan: 20
minecraft:fire_coral_fan: 20
minecraft:horn_coral_fan: 20
minecraft:dead_tube_coral_fan: 1
minecraft:dead_brain_coral_fan: 1
minecraft:dead_bubble_coral_fan: 1
minecraft:dead_fire_coral_fan: 1
minecraft:dead_horn_coral_fan: 1

# Transportation
minecraft:saddle: 600
minecraft:elytra: 20000
minecraft:iron_horse_armor: 400
minecraft:golden_horse_armor: 800
minecraft:diamond_horse_armor: 1200

# Netherite tools & armor (disabled because made of diamonds)
minecraft:netherite_sword: -1
minecraft:netherite_shovel: -1
minecraft:netherite_pickaxe: -1
minecraft:netherite_axe: -1
minecraft:netherite_hoe: -1
minecraft:netherite_helmet: -1
minecraft:netherite_chestplate: -1
minecraft:netherite_leggings: -1
minecraft:netherite_boots: -1

# Chaimail armor
minecraft:chainmail_helmet: 500
minecraft:chainmail_chestplate: 800
minecraft:chainmail_leggings: 700
minecraft:chainmail_boots: 400

# Food
minecraft:apple: 20
minecraft:wheat_seeds: 2
minecraft:porkchop: 20
minecraft:cooked_porkchop: 20
minecraft:enchanted_golden_apple: 1000
minecraft:cod: 20
minecraft:salmon: 20
minecraft:tropical_fish: 20
minecraft:pufferfish: 20
minecraft:cooked_cod: 20
minecraft:cooked_salmon: 20
minecraft:melon_slice: 5
minecraft:beef: 20
minecraft:cooked_beef: 20
minecraft:chicken: 20
minecraft:cooked_chicken: 20
minecraft:carrot: 10
minecraft:potato: 10
minecraft:baked_potato: 10
minecraft:poisonous_potato: 1
minecraft:rabbit: 20
minecraft:cooked_rabbit: 20
minecraft:mutton: 20
minecraft:cooked_mutton: 20
minecraft:chorus_fruit: 20
minecraft:popped_chorus_fruit: 20
minecraft:beetroot: 20
minecraft:beetroot_seeds: 2
minecraft:suspicious_stew: 10
minecraft:sweet_berries: 5
minecraft:glow_berries: 20

# Loot
minecraft:string: 10
minecraft:feather: 5
minecraft:gunpowder: 10
minecraft:sponge: 200
minecraft:wet_sponge: 200
minecraft:egg: 5
minecraft:ink_sac: 5
minecraft:glow_ink_sac: 100
minecraft:bone: 5
minecraft:rotten_flesh: 5
minecraft:ender_pearl: 80
minecraft:blaze_rod: 30
minecraft:ghast_tear: 80
minecraft:spider_eye: 5
minecraft:skeleton_skull: 40
minecraft:wither_skeleton_skull: 300
minecraft:zombie_head: 40
minecraft:creeper_head: 40
minecraft:dragon_head: 200
minecraft:nether_star: 1000
minecraft:rabbit_foot: 100
minecraft:rabbit_hide: 5
minecraft:totem_of_undying: 2000
minecraft:shulker_shell: 250
minecraft:trident: 1000
minecraft:phantom_membrane: 100
minecraft:nautilus_shell: 30
minecraft:heart_of_the_sea: 1000

# Materials
minecraft:charcoal: 20
minecraft:scute: 100
minecraft:flint: 5
minecraft:quartz: 20
minecraft:amethyst_shard: 50
minecraft:netherite_scrap: 1000
minecraft:snowball: 1
minecraft:clay_ball: 5
minecraft:brick: 5
minecraft:glowstone_dust: 10
minecraft:nether_brick: 1
minecraft:prismarine_shard: 20
minecraft:prismarine_crystals: 20
minecraft:firework_star: 10
minecraft:dragon_breath: 100

# Filled buckets
minecraft:water_bucket: 150
minecraft:lava_bucket: 150
minecraft:milk_bucket: 150
minecraft:pufferfish_bucket: 150
minecraft:salmon_bucket: 150
minecraft:cod_bucket: 150
minecraft:tropical_fish_bucket: 150
minecraft:axolotl_bucket: 150
minecraft:powder_snow_bucket: 150

# Dyes
minecraft:green_dye: 1

# Items
minecraft:filled_map: 250
minecraft:potion: -1
minecraft:experience_bottle: 100
minecraft:written_book: -1
minecraft:enchanted_book: -1
minecraft:name_tag: 500
minecraft:splash_potion: -1
minecraft:tipped_arrow: -1
minecraft:lingering_potion: -1
minecraft:globe_banner_pattern: 200
minecraft:piglin_banner_pattern: 200

# Music discs
minecraft:music_disc_13: 1000
minecraft:music_disc_cat: 1000
minecraft:music_disc_blocks: 1000
minecraft:music_disc_chirp: 1000
minecraft:music_disc_far: 1000
minecraft:music_disc_mall: 1000
minecraft:music_disc_mellohi: 1000
minecraft:music_disc_stal: 1000
minecraft:music_disc_strad: 1000
minecraft:music_disc_ward: 1000
minecraft:music_disc_11: 1000
minecraft:music_disc_wait: 1000
minecraft:music_disc_otherside: 1000
minecraft:music_disc_pigstep: 1000

# Spawn eggs
minecraft:axolotl_spawn_egg: -1
minecraft:bat_spawn_egg: -1
minecraft:bee_spawn_egg: -1
minecraft:blaze_spawn_egg: -1
minecraft:cat_spawn_egg: -1
minecraft:cave_spider_spawn_egg: -1
minecraft:chicken_spawn_egg: -1
minecraft:cod_spawn_egg: -1
minecraft:cow_spawn_egg: -1
minecraft:creeper_spawn_egg: -1
minecraft:dolphin_spawn_egg: -1
minecraft:donkey_spawn_egg: -1
minecraft:drowned_spawn_egg: -1
minecraft:elder_guardian_spawn_egg: -1
minecraft:enderman_spawn_egg: -1
minecraft:endermite_spawn_egg: -1
minecraft:evoker_spawn_egg: -1
minecraft:fox_spawn_egg: -1
minecraft:ghast_spawn_egg: -1
minecraft:glow_squid_spawn_egg: -1
minecraft:goat_spawn_egg: -1
minecraft:guardian_spawn_egg: -1
minecraft:hoglin_spawn_egg: -1
minecraft:horse_spawn_egg: -1
minecraft:husk_spawn_egg: -1
minecraft:llama_spawn_egg: -1
minecraft:magma_cube_spawn_egg: -1
minecraft:mooshroom_spawn_egg: -1
minecraft:mule_spawn_egg: -1
minecraft:ocelot_spawn_egg: -1
minecraft:panda_spawn_egg: -1
minecraft:parrot_spawn_egg: -1
minecraft:phantom_spawn_egg: -1
minecraft:pig_spawn_egg: -1
minecraft:piglin_spawn_egg: -1
minecraft:piglin_brute_spawn_egg: -1
minecraft:pillager_spawn_egg: -1
minecraft:polar_bear_spawn_egg: -1
minecraft:pufferfish_spawn_egg: -1
minecraft:rabbit_spawn_egg: -1
minecraft:ravager_spawn_egg: -1
minecraft:salmon_spawn_egg: -1
minecraft:sheep_spawn_egg: -1
minecraft:shulker_spawn_egg: -1
minecraft:silverfish_spawn_egg: -1
minecraft:skeleton_spawn_egg: -1
minecraft:skeleton_horse_spawn_egg: -1
minecraft:slime_spawn_egg: -1
minecraft:spider_spawn_egg: -1
minecraft:squid_spawn_egg: -1
minecraft:stray_spawn_egg: -1
minecraft:strider_spawn_egg: -1
minecraft:trader_llama_spawn_egg: -1
minecraft:tropical_fish_spawn_egg: -1
minecraft:turtle_spawn_egg: -1
minecraft:vex_spawn_egg: -1
minecraft:villager_spawn_egg: -1
minecraft:vindicator_spawn_egg: -1
minecraft:wandering_trader_spawn_egg: -1
minecraft:witch_spawn_egg: -1
minecraft:wither_skeleton_spawn_egg: -1
minecraft:wolf_spawn_egg: -1
minecraft:zoglin_spawn_egg: -1
minecraft:zombie_spawn_egg: -1
minecraft:zombie_horse_spawn_egg: -1
minecraft:zombie_villager_spawn_egg: -1
minecraft:zombified_piglin_spawn_egg: -1

# Creative
minecraft:command_block: -1
minecraft:repeating_command_block: -1
minecraft:chain_command_block: -1
minecraft:warped_wart_block: -1
minecraft:structure_void: -1
minecraft:end_portal_frame: -1
minecraft:dirt_path: -1
minecraft:barrier: -1
minecraft:light: -1
minecraft:structure_block: -1
minecraft:jigsaw: -1
minecraft:player_head: -1
minecraft:command_block_minecart: -1
minecraft:knowledge_book: -1
minecraft:debug_stick: -1

# Game experiment
minecraft:sculk_sensor: -1
minecraft:bundle: -1
