# Missing roots due to circular references:
minecraft:raw_iron: 50
minecraft:iron_ingot: 50
minecraft:coal: 10
minecraft:raw_gold: 100
minecraft:gold_ingot: 100
minecraft:raw_copper: 25
minecraft:copper_ingot: 25
minecraft:diamond: -1
minecraft:emerald: 200
minecraft:lapis_lazuli: 20
minecraft:redstone: 10
minecraft:slime_ball: 20
minecraft:wheat: 5
minecraft:kelp: 5
minecraft:dried_kelp: 5
minecraft:honey_bottle: 20

# Balancing:
minecraft:granite: 1
minecraft:diorite: 1
minecraft:andesite: 1

# Duplicable items:
minecraft:powered_rail: -1
minecraft:detector_rail: -1
minecraft:rail: -1
minecraft:activator_rail: -1
minecraft:white_carpet: -1
minecraft:orange_carpet: -1
minecraft:magenta_carpet: -1
minecraft:light_blue_carpet: -1
minecraft:yellow_carpet: -1
minecraft:lime_carpet: -1
minecraft:pink_carpet: -1
minecraft:gray_carpet: -1
minecraft:light_gray_carpet: -1
minecraft:cyan_carpet: -1
minecraft:purple_carpet: -1
minecraft:blue_carpet: -1
minecraft:brown_carpet: -1
minecraft:green_carpet: -1
minecraft:red_carpet: -1
minecraft:black_carpet: -1
